version: "3"

services:
  ##########################
  ### SETUP SERVER CONTAINER
  ##########################
  server:
    container_name: kiwe-node-express
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    env_file: ./server/.env
    environment:
      NODE_ENV: development
    ports:
      - 5000:5000
    volumes:
      - ./server:/usr/app/server
      - /usr/app/server/node_modules
    # depends_on:
    #   - mongo
    command: npm run backend
  ##########################
  ### SETUP CLIENT CONTAINER
  ##########################
  client:
    container_name: kiwe-react-client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    env_file: ./client/.env
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/app/client
      - /usr/app/client/node_modules
    depends_on:
      - server
    stdin_open: true # exited with code 0 해결
    tty: true # exited with code 0 해결
    command: npm run start
  ##########################
  ### SETUP DB CONTAINER
  ##########################
  # mongo:
  #   image: mongo
  #   container_name: kiwe-mongodb
  #   ports:
  #     - "27017:27017"
