version: "3"

services:
  ##########################
  ### SETUP CLIENT CONTAINER
  ##########################
  # client:
  #   build:
  #     context: ./client
  #   ports:
  #     - "80:80"
  #   networks:
  #     - client
  #     - server

  ##########################
  ### SETUP SERVER CONTAINER
  ##########################
  server:
    container_name: kiwe-prod-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file: ./server/.env
    environment:
      NODE_ENV: production
#     networks:
#       - server

# networks:
#   client:
#   server:
