version: "3"

services:
  ##########################
  ### SETUP SERVER CONTAINER
  ##########################
  server:
    container_name: kiwe-server
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    env_file: ./server/.env
    environment:
      NODE_ENV: production
    restart: always

  ##########################
  ### SETUP CLIENT(NGINX) CONTAINER
  ##########################
  client:
    container_name: kiwe-nginx
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    links:
      - server
    restart: always
